apiVersion: v2
version: 1.0.4
appVersion: 19.0.2
description: A modern software package to manage your company or foundation's activity
home: https://www.dolibarr.org/
icon: https://raw.githubusercontent.com/Dolibarr/dolibarr/develop/doc/images/dolibarr_256x256_color.svg
maintainers:
  - name: Sören Metje
    email: soerenmetje@yahoo.de
name: dolibarr
sources:
  - https://github.com/Dolibarr/dolibarr
  - https://github.com/soerenmetje/helm-charts/tree/master/charts/dolibarr
  - https://github.com/cowboysysop/charts/tree/master/charts/dolibarr
dependencies:
  - name: common
    version: 2.19.2
    repository: https://charts.bitnami.com/bitnami/
  - name: mariadb
    version: 18.0.6
    repository: https://charts.bitnami.com/bitnami/
    condition: mariadb.enabled
annotations:
  artifacthub.io/signKey: |
    fingerprint: 61F2C4B5DAB61E96DAE9FCDB3DFBC2E2EA612765
    url: https://soerenmetje.github.io/helm-charts/gpg-public-key.asc
  kubeVersion: ">=1.24"
